export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const ARTICLES_FETCH_SUCCESS = 'ARTICLES_FETCH_SUCCESS';
export const ARTICLES_FETCH_FAIL = 'ARTICLES_FETCH_FAIL';
export const SAVE_ARTICLE = 'SAVE_ARTICLE';
