export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const GET_SCRAPINGS = 'GET_SCRAPINGS';
export const ARTICLES_FETCH_SUCCESS = 'ARTICLES_FETCH_SUCCESS';
export const ARTICLES_FETCH_FAIL = 'ARTICLES_FETCH_FAIL';
export const SAVE_ARTICLE = 'SAVE_ARTICLE';
export const SCRAPE_SUCCESS = 'SCRAPE_SUCCESS';
export const SCRAPE_FAILURE = 'SCRAPE_FAILURE';
